### ISSUE TITLE
Returning **Not Found** on shortened Link if the longest link it's without the "https://"

### ISSUE THREAD

**Issue by W4rL0ck1** [angeloevangelista/pitu#1]
The Application is returning **Not Found** if the longest link its without the "https://" before the address, maybe the application don't recognize that the address its a link without the "https://" in it.

**Comment by angeloevangelista** [comment]
@W4rL0ck1

Hey! Let's celebrate, this error is done. 🎉🎉

This bug was fixed here: e474a67f3bc683d84db9e1ba6fe9c81750ce5817
The solution was basically enforce `http://` protocol in links doesn't have the protocol. E.g.: `www.facebook.com`. 

To keep the confiability of the stored link, the API checks if the result link aims to a valid endpoint, checking if there is a response when accessed through `GET` method.

For now, I'll close this issue, but be free to reopen if necessary. Thanks to contribute! 😉
